# Generated by Django 2.2.5 on 2020-12-02 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0002_auto_20201202_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='room',
            new_name='room_number',
        ),
    ]
