# Generated by Django 2.2.5 on 2021-01-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0003_auto_20201202_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room',
            field=models.CharField(choices=[(1, 'Room type'), (2, 'Single occupation'), (3, 'Double occupation'), (4, 'Both occupation')], default='Single occupation', max_length=64),
        ),
    ]
