# Generated by Django 2.2.5 on 2020-11-27 10:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_auto_20201127_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='fullname',
        ),
        migrations.AddField(
            model_name='hotels',
            name='photo_inside',
            field=models.ImageField(blank=True, null=True, upload_to='hotels/'),
        ),
        migrations.AddField(
            model_name='hotels',
            name='photo_outside',
            field=models.ImageField(blank=True, null=True, upload_to='hotels/'),
        ),
        migrations.AddField(
            model_name='hotels',
            name='photo_room',
            field=models.ImageField(blank=True, null=True, upload_to='hotels/'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
