# Generated by Django 2.2.5 on 2020-11-30 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_auto_20201127_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quarters',
            name='state',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='client',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='room',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='states',
            name='province',
        ),
        migrations.DeleteModel(
            name='Hotels',
        ),
        migrations.DeleteModel(
            name='Provinces',
        ),
        migrations.DeleteModel(
            name='Quarters',
        ),
        migrations.DeleteModel(
            name='Reservations',
        ),
        migrations.DeleteModel(
            name='Rooms',
        ),
        migrations.DeleteModel(
            name='States',
        ),
    ]
